blank_issues_enabled: true
contact_links:
  - name: Report a security vulnerability
    url: https://github.com/fyulita/dateframe/security/advisories/new
    about: Privately report vulnerabilities or issues that risk exposing or damaging personal media.

